### ISSUE TITLE
Setup fails - dependency service does not exist or has been marked for deletion

### ISSUE THREAD

**Issue by madrxx** [jackyaz/DisplaySwitchVNC#3]
![image](https://github.com/jackyaz/DisplaySwitchVNC/assets/74277456/fe807388-d336-4446-b0bf-d680dd7ec948)
Previously used this tool on my Windows 10 installation having installed it ages ago and since updated to the latest version of RVNC Connect with no problems whatsoever, But, on trying to set it up on a new Windows 11 machine with latest RVNC Connect, setup fails with "The dependency service does not exist or has been marked for deletion"

**Comment by jackyaz** [comment]
Hi, I believe this is due to the rename of the service from VNC Server to RealVNC Server. I'll dust off the code for this and see if I can fix it up for v7 RealVNC Server

**Comment by madrxx** [comment]
Brilliant, thank you very much. I appreciate this app a lot :)

**Comment by jackyaz** [comment]
Can you try v6.0.6 please? https://github.com/jackyaz/DisplaySwitchVNC/releases/tag/v6.0.6

**Comment by madrxx** [comment]
Works perfectly, thanks!
